# Generated by Django 4.2.7 on 2025-03-31 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('language', models.CharField(max_length=50)),
                ('confidence', models.IntegerField(default=1)),
                ('learned', models.BooleanField(default=False)),
                ('times_practiced', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_practiced'],
                'unique_together': {('user', 'word', 'language')},
            },
        ),
    ]
