# Generated by Django 5.0 on 2025-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
