# Generated by Django 5.0 on 2025-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0002_word_next_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='confidence',
        ),
        migrations.AddField(
            model_name='word',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='word',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
