# Generated by Django 5.0 on 2025-04-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0003_remove_word_confidence_word_ease_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='confidence',
            field=models.IntegerField(default=1),
        ),
    ]
