# Generated by Django 5.0 on 2025-04-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0004_word_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='ease_factor',
        ),
        migrations.RemoveField(
            model_name='word',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='word',
            name='repetitions',
        ),
    ]
