# Generated by Django 5.0 on 2025-04-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0005_remove_word_ease_factor_remove_word_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='exampleSentenceTranslation',
            field=models.TextField(blank=True),
        ),
    ]
