# Generated by Django 4.2.7 on 2025-03-31 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('words_added', models.IntegerField(default=0)),
                ('words_practiced', models.IntegerField(default=0)),
                ('words_mastered', models.IntegerField(default=0)),
                ('stories_read', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('daily_goal_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Activities',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
